?key: WORD -> key
?value:     array
         |  range
         |  glob
         |  primitive
            
?array: "[" (primitive ",")* primitive "]"

?range:     int "-" int "-" int
         |  int ".." int ".." int

?glob: /.*[*].*/ -> glob
            
?primitive:  float
         |   int
         |   word
         |   bool

word: WORD
float: FLOAT
int: INT
bool.2: BOOL

%import .terminals.WORD
%import .terminals.FLOAT
%import .terminals.INT
%import .terminals.BOOL