"""
Parity tests of the MSD class against reference data generated with
the legacy thh_tools Diffcalc binary.

The reference data in tests/data/msd was generated by running the
legacy Diffcalc tool (compiled with -O2) with the checked-in input
files diffcalc_O.in, diffcalc_atom3.in and diffcalc_O_start.in on
the checked-in trajectory traj.xyz (40 atoms with alternating O/H
names performing a wrapped random walk in an orthorhombic box of
20 Angstrom over 500 frames).
"""

import hashlib
import sys

import numpy as np
import pytest

from PQAnalysis.analysis.msd import MSD
from PQAnalysis.io import TrajectoryReader

from .. import pytestmark  # pylint: disable=unused-import

msd_module = sys.modules[MSD.__module__]

#: The raw analysis path and the legacy tool both parse coordinates as
#: float64. The remaining tolerance is one half-unit in the last place
#: printed by the eight-decimal legacy reference files, plus a small
#: numerical margin.
RTOL = 0.0
ATOL = 5.1e-9

#: SHA-256 digests of little-endian float64 component values emitted by
#: Diffcalc compiled with -O2 and printed as C99 hexadecimal floats.
MSD_FLOAT64_SHA256 = {
    "O": "b0aa55a6e2967f267bd4c2a3200b8ddf71bccedd23226d783a8e386960c48f66",
    "atom3": "bce49c957358f48c7f63f727c1752f9d1a53a499c9e4c6d1b133faa937e49f0d",
    "O_start": "458bb4ffad296e7161e971faa5fb25becd2aadd22d682696d20bf5f8cddbf12a",
}



def _run_msd(target_species, **kwargs):
    """
    Runs an MSD analysis on the reference trajectory.
    """
    reader = TrajectoryReader("traj.xyz")
    msd = MSD(reader, target_species, window=100, gap=10, **kwargs)
    _, msd_x, msd_y, msd_z, _ = msd.run()

    return np.column_stack([msd_x, msd_y, msd_z])


def _float64_sha256(values):
    """Returns a platform-independent digest of float64 result bits."""
    array = np.asarray(values, dtype="<f8")

    return hashlib.sha256(array.tobytes(order="C")).hexdigest()



class TestMSDLegacyParity:

    """
    Parity tests of the MSD class against the legacy Diffcalc tool.
    """

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_name_selection_matches_legacy(self, test_with_data_dir):
        reference = np.loadtxt("msd_ref_O.dat")

        result = _run_msd("O")

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)

        if msd_module.direct_msd_lag_range is not None:
            assert _float64_sha256(result) == MSD_FLOAT64_SHA256["O"]

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_index_selection_matches_legacy(self, test_with_data_dir):
        # the legacy Diffcalc target_atoms indices are 0-based,
        # exactly like the PQAnalysis selection indices
        reference = np.loadtxt("msd_ref_atom3.dat")

        result = _run_msd(np.array([3]))

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)

        if msd_module.direct_msd_lag_range is not None:
            assert _float64_sha256(result) == MSD_FLOAT64_SHA256["atom3"]

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_n_start_matches_legacy(self, test_with_data_dir):
        # legacy 'start = 155;' delays the origin spawning to the
        # first multiple of the gap >= 155 but intentionally keeps
        # the normalization by total_origins = stop_frame // gap
        reference = np.loadtxt("msd_ref_O_start.dat")

        result = _run_msd("O", n_start=155)

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)

        if msd_module.direct_msd_lag_range is not None:
            assert _float64_sha256(result) == MSD_FLOAT64_SHA256["O_start"]

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_exact_streaming_full_precision(
        self,
        test_with_data_dir,
        monkeypatch,
    ):
        monkeypatch.setattr(MSD, "_direct_batch_max_bytes", 0)

        result = _run_msd("O")
        reference = np.loadtxt("msd_ref_O.dat")

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)

        if msd_module.legacy_msd_frame_update is not None:
            assert _float64_sha256(result) == MSD_FLOAT64_SHA256["O"]
