"""
Parity tests of the MSD class against reference data generated with
the legacy thh_tools Diffcalc binary.

The reference data in tests/data/msd was generated by running the
legacy Diffcalc tool (compiled with -O2) with the checked-in input
files diffcalc_O.in, diffcalc_atom3.in and diffcalc_O_start.in on
the checked-in trajectory traj.xyz (40 atoms with alternating O/H
names performing a wrapped random walk in an orthorhombic box of
20 Angstrom over 500 frames).
"""

import numpy as np
import pytest

from PQAnalysis.analysis.msd import MSD
from PQAnalysis.io import TrajectoryReader

from .. import pytestmark  # pylint: disable=unused-import

#: The tolerances of the parity tests. PQAnalysis parses coordinates
#: as float32 while the legacy tool parses them as double, so exact
#: equality cannot be expected. The observed maximum absolute
#: deviation is below 1e-6 for MSD values of the order of 10.
RTOL = 1e-5
ATOL = 5e-6



def _run_msd(target_species, **kwargs):
    """
    Runs an MSD analysis on the reference trajectory.
    """
    reader = TrajectoryReader("traj.xyz")
    msd = MSD(reader, target_species, window=100, gap=10, **kwargs)
    _, msd_x, msd_y, msd_z, _ = msd.run()

    return np.column_stack([msd_x, msd_y, msd_z])



class TestMSDLegacyParity:

    """
    Parity tests of the MSD class against the legacy Diffcalc tool.
    """

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_name_selection_matches_legacy(self, test_with_data_dir):
        reference = np.loadtxt("msd_ref_O.dat")

        result = _run_msd("O")

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_index_selection_matches_legacy(self, test_with_data_dir):
        # the legacy Diffcalc target_atoms indices are 0-based,
        # exactly like the PQAnalysis selection indices
        reference = np.loadtxt("msd_ref_atom3.dat")

        result = _run_msd(np.array([3]))

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)

    @pytest.mark.parametrize("example_dir", ["msd"], indirect=False)
    def test_n_start_matches_legacy(self, test_with_data_dir):
        # legacy 'start = 155;' delays the origin spawning to the
        # first multiple of the gap >= 155 but intentionally keeps
        # the normalization by total_origins = stop_frame // gap
        reference = np.loadtxt("msd_ref_O_start.dat")

        result = _run_msd("O", n_start=155)

        assert np.allclose(result, reference[:, 1:], rtol=RTOL, atol=ATOL)
